version: '3.8'

services:
  website1:
    build: ./zomato-web-app
    image: website1-image
    container_name: website1
    ports:
      - "8081:80"
    volume:
      - ./Amazon-clone:/app
    network:
      - my_network
    depends_on:
      - website2

  website2:
    build: ./Amazon-Clone
    image: website2-image
    container_name: website2
    ports:
      - "8082:80"
    volumes:
      - ./Amazon-clone:/app
    networks:
      - my_network

volume:
  my_volume:
    driver: local

network:
  my_network:
    driver: bridge
