version: '3.8'

services:
  website1:
    build:
      context: ./zomato-web-app
      dockerfile: Dockerfile
    image: website1-image:latest
    container_name: website1
    ports:
      - "8081:80"

  website2:
    build:
      context: ./Amazon-Clone
      dockerfile: Dockerfile
    image: website2-image:latest
    container_name: website2
    ports:
      - "8082:80"
